if (NOT DEFINED NIMBUS_ROOT_DIR)
    set(NIMBUS_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE STRING "Nimbus root directory")
endif ()

if (NOT DEFINED NIMBUS_ENGINE_ROOT_DIR)
    set(NIMBUS_ENGINE_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE STRING "Nimbus engines root directory")
endif ()

if (NOT DEFINED NIMBUS_EDITOR_ROOT_DIR)
    set(NIMBUS_EDITOR_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE STRING "Nimbus editors root directory")
endif ()

if (NOT DEFINED NIMBUS_GAME_ROOT_DIR)
    set(NIMBUS_GAME_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE STRING "Nimbus games root directory")
endif ()

if (NOT DEFINED NIMBUS_LAUNCHER_ROOT_DIR)
    set(NIMBUS_LAUNCHER_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR} CACHE STRING "Nimbus launchers root directory")
endif ()